version: 2.1
jobs:
  docker: # it uses the docker executor
      - image: circleci/ruby:2.4.1
  howdy:
    steps:
      - checkout
      - run: echo 'Howdy first of all'
  rowdy:
    docker: # it uses the docker executor
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo 'Triple threat'
workflows:
  version: 2.1
  howdy_rowdy:
    jobs:
      - howdy
      - rowdy