version: 2.1
jobs:
  build:
    docker: # it uses the docker executor
      - image: circleci/node:14.17.5
    steps:
      - checkout
      - run: echo 'npm installing'
      - run: npm install
      - run: CI=true npm run build
  test:
    docker: # it uses the docker executor
      - image: circleci/node:14.17.5
    steps:
      - checkout
      - run: echo 'testing stuff'
      - run: npm install
      - run: npm test
  test2:
    docker: # it uses the docker executor
      - image: circleci/node:14.17.5 
    steps:
      - checkout
      - run: echo 'test2...'
workflows:
  version: 2.1
  build_test_lint:
    jobs:
      - build
      - test2
      - test:
          requires:
            - test2