version: 2.1
orb:
  - node: circleci/node@4.1
jobs:
  howdy:
    steps:
      - checkout
      - run: echo 'Howdy first of all'
  rowdy:
    steps:
      - checkout
      - run: echo 'Triple threat'
workflows:
  version: 2.1
  howdy_rowdy:
    jobs:
      - howdy
      - rowdy